project:
  type: book

from: markdown+emoji

book:
  title: "Pythonmatte"
  subtitle: "Programmering i matematikk programfag på vgs"
  author: "Torodd F. Ottestad"
  favicon: img/programmer.png

  
  repo-url: https://github.com/lektorodd/mattebok
  repo-branch: main
  repo-actions: [source, issue]
  sharing: [twitter, facebook]
  downloads: pdf
  sidebar: 
      logo: img/programmer.png

  chapters:
    - index.qmd
    - part: sannsyn1.qmd
      chapters: 
        - sannsyn-terningar.ipynb
        - sannsyn-samansette_forsok.ipynb
        - sannsyn-ulike_fordelingar.ipynb
        - sannsyn-hypotesetesting.ipynb
    - part: folgerogrekker.qmd
      chapters: 
      - følger.ipynb
      - rekker1.ipynb
    - part: funksjonar.qmd
      chapters: 
      - funksjonar-plotting_og_modellering.ipynb
      - funksjonar-derivasjon.ipynb
      - funksjonar-integrasjon.ipynb
  appendices:
    - miniconda.qmd
    
  google-analytics:
    tracking-id: "G-NHM0JJCVM6"
    anonymize-ip: true


format:
  html:
    theme: 
    - cosmo
    - custom.scss
    code-line-numbers: true
  pdf:
    documentclass: scrreprt
    code-line-numbers: true
execute:
  freeze: auto 


