project:
  type: book

from: markdown+emoji

book:
  title: "Pythonmatte"
  subtitle: "Programmering i matematikk programfag på vgs"
  author: "Torodd F. Ottestad"
  
  repo-url: https://github.com/lektorodd/mattebok
  repo-branch: main
  repo-actions: [source, issue]
  sharing: [twitter, facebook]
  downloads: pdf
  sidebar: 
      logo: img/programmer.png

  chapters:
    - index.qmd
    - part: sannsyn1.qmd
      chapters: 
        - sannsyn-terningar.ipynb
    - summary.qmd


format:
  html:
    theme: 
    - cosmo
    - cutsom.scss
  pdf:
    documentclass: scrreprt



